### ISSUE TITLE
Bỏ ràng buộc

### ISSUE THREAD

**Issue by QHuy69** [AikoPanelv1/AikoPanel#2]
bỏ SNI bắt buộc ở plan
bỏ sni mặc định ở edit user
thêm mới tính năng báo số user trêm server hằng giờ qua gr

**Comment by QHuy69** [comment]
fix lỗi bot tele không bind được

**Comment by Github-Aiko** [comment]
Kê

**Comment by QHuy69** [comment]
Thêm tính năng set khoảng thời gian bot báo user về cho telegram admin

**Comment by Github-Aiko** [comment]
> Thêm tính năng set khoảng thời gian bot báo user về cho telegram admin

Cái này à đang hên xui để xem thử nào chưa thử đa số t toàn import thư viện

**Comment by Github-Aiko** [comment]
Update ở 2.6.7 beta 2 gồm 2 nội dung
- bỏ SNI bắt buộc ở plan
- bỏ sni mặc định ở edit user

> bỏ SNI bắt buộc ở plan bỏ sni mặc định ở edit user thêm mới tính năng báo số user trêm server hằng giờ qua gr

**Comment by Github-Aiko** [comment]
Done ALL
