### ISSUE TITLE
Thêm tính năng

### ISSUE THREAD

**Issue by QHuy69** [AikoPanelv1/AikoPanel#3]
Thêm tính năng tự động off node nếu node đó trong khoảng thời gian nào đó không có user sử dụng
tạo box để set time

**Comment by Github-Aiko** [comment]
Pending ….

**Comment by Github-Aiko** [comment]
Chưa khả thi đang xem xét lại thuật toán sau khi fix full lỗi hiện hành

**Comment by Github-Aiko** [comment]
Done OFF ISSUES
