### ISSUE TITLE
Fix lỗi & Thêm tính năng

### ISSUE THREAD

**Issue by AZZ-vopp** [AikoPanelv1/AikoPanel#4]
lỗi hiện thông tin gói trên shadowrocket vĩnh viễn nó lại hiện 1-1-1970
fix lỗi không hiện ip đang kết nối trên web user
trên trang user góp ý thêm hiện số người dùng trên web và trên trang admin có nút tắt bật
trên chỗ hệ thống máy chủ lên cho hiện luôn hình cờ ( đang vị icon text)
thêm tính năng mã giảm giá theo link giới thiệu ( chỉ cso đăng ký theo link đó mới nhập được mã giảm giá )
cảm ơn Aiko đã xem :))

**Comment by Github-Aiko** [comment]
Cái thứ 3 không khả thi còn lại thì ok không vấn đề chờ next commit

**Comment by Github-Aiko** [comment]
Done : lỗi hiện thông tin gói trên shadowrocket vĩnh viễn nó lại hiện 1-1-1970
