### ISSUE TITLE
Lỗi update

### ISSUE THREAD

**Issue by codevvj** [AikoPanelv1/AikoPanel#5]
![Ảnh chụp màn hình 2023-11-27 013745](https://github.com/AikoPanel/AikoPanel/assets/111896608/28b32660-4fce-4b20-ab85-013be8ec83c8)

**Comment by Github-Aiko** [comment]
Install : composer require doctrine/dbal 

- Ngày mai sẽ có commit fix

**Comment by Github-Aiko** [comment]
Fix done update At : v2.6.8
